name: DS
services:
    rotate_certificate:
        build: .
        container_name: rotate_certificate
        ports:
          - "127.0.0.1:8000:8000"
        volumes:
          - ../service/src:/src
          - ../service/rot_imgs:/rot_imgs
        entrypoint: uvicorn src.main:app --host="0.0.0.0"
